-- MySQL Script generated by MySQL Workbench
-- Sun Oct 19 17:10:34 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema kitty_glow_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `kitty_glow_db` ;

-- -----------------------------------------------------
-- Schema kitty_glow_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kitty_glow_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci ;
SHOW WARNINGS;
USE `kitty_glow_db` ;

-- -----------------------------------------------------
-- Table `kitty_glow_db`.`auth_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kitty_glow_db`.`auth_group` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `kitty_glow_db`.`auth_group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `name` ON `kitty_glow_db`.`auth_group` (`name` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `kitty_glow_db`.`django_content_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kitty_glow_db`.`django_content_type` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `kitty_glow_db`.`django_content_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `app_label` VARCHAR(100) NOT NULL,
  `model` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `django_content_type_app_label_model_76bd3d3b_uniq` ON `kitty_glow_db`.`django_content_type` (`app_label` ASC, `model` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `kitty_glow_db`.`auth_permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kitty_glow_db`.`auth_permission` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `kitty_glow_db`.`auth_permission` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `content_type_id` INT NOT NULL,
  `codename` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `auth_permission_content_type_id_2f476e4b_fk_django_co`
    FOREIGN KEY (`content_type_id`)
    REFERENCES `kitty_glow_db`.`django_content_type` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 53
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `auth_permission_content_type_id_codename_01ab375a_uniq` ON `kitty_glow_db`.`auth_permission` (`content_type_id` ASC, `codename` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `kitty_glow_db`.`auth_group_permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kitty_glow_db`.`auth_group_permissions` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `kitty_glow_db`.`auth_group_permissions` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `group_id` INT NOT NULL,
  `permission_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `auth_group_permissio_permission_id_84c5c92e_fk_auth_perm`
    FOREIGN KEY (`permission_id`)
    REFERENCES `kitty_glow_db`.`auth_permission` (`id`),
  CONSTRAINT `auth_group_permissions_group_id_b120cbf9_fk_auth_group_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `kitty_glow_db`.`auth_group` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `auth_group_permissions_group_id_permission_id_0cd325b0_uniq` ON `kitty_glow_db`.`auth_group_permissions` (`group_id` ASC, `permission_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `auth_group_permissio_permission_id_84c5c92e_fk_auth_perm` ON `kitty_glow_db`.`auth_group_permissions` (`permission_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `kitty_glow_db`.`auth_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kitty_glow_db`.`auth_user` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `kitty_glow_db`.`auth_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(128) NOT NULL,
  `last_login` DATETIME(6) NULL DEFAULT NULL,
  `is_superuser` TINYINT(1) NOT NULL,
  `username` VARCHAR(150) NOT NULL,
  `first_name` VARCHAR(150) NOT NULL,
  `last_name` VARCHAR(150) NOT NULL,
  `email` VARCHAR(254) NOT NULL,
  `is_staff` TINYINT(1) NOT NULL,
  `is_active` TINYINT(1) NOT NULL,
  `date_joined` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `username` ON `kitty_glow_db`.`auth_user` (`username` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `kitty_glow_db`.`auth_user_groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kitty_glow_db`.`auth_user_groups` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `kitty_glow_db`.`auth_user_groups` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `group_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `auth_user_groups_group_id_97559544_fk_auth_group_id`
    FOREIGN KEY (`group_id`)
    REFERENCES `kitty_glow_db`.`auth_group` (`id`),
  CONSTRAINT `auth_user_groups_user_id_6a12ed8b_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `kitty_glow_db`.`auth_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `auth_user_groups_user_id_group_id_94350c0c_uniq` ON `kitty_glow_db`.`auth_user_groups` (`user_id` ASC, `group_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `auth_user_groups_group_id_97559544_fk_auth_group_id` ON `kitty_glow_db`.`auth_user_groups` (`group_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `kitty_glow_db`.`auth_user_user_permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kitty_glow_db`.`auth_user_user_permissions` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `kitty_glow_db`.`auth_user_user_permissions` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `permission_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm`
    FOREIGN KEY (`permission_id`)
    REFERENCES `kitty_glow_db`.`auth_permission` (`id`),
  CONSTRAINT `auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `kitty_glow_db`.`auth_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `auth_user_user_permissions_user_id_permission_id_14a6b632_uniq` ON `kitty_glow_db`.`auth_user_user_permissions` (`user_id` ASC, `permission_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm` ON `kitty_glow_db`.`auth_user_user_permissions` (`permission_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `kitty_glow_db`.`django_admin_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kitty_glow_db`.`django_admin_log` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `kitty_glow_db`.`django_admin_log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `action_time` DATETIME(6) NOT NULL,
  `object_id` LONGTEXT NULL DEFAULT NULL,
  `object_repr` VARCHAR(200) NOT NULL,
  `action_flag` SMALLINT UNSIGNED NOT NULL,
  `change_message` LONGTEXT NOT NULL,
  `content_type_id` INT NULL DEFAULT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `django_admin_log_content_type_id_c4bce8eb_fk_django_co`
    FOREIGN KEY (`content_type_id`)
    REFERENCES `kitty_glow_db`.`django_content_type` (`id`),
  CONSTRAINT `django_admin_log_user_id_c564eba6_fk_auth_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `kitty_glow_db`.`auth_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;

SHOW WARNINGS;
CREATE INDEX `django_admin_log_content_type_id_c4bce8eb_fk_django_co` ON `kitty_glow_db`.`django_admin_log` (`content_type_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `django_admin_log_user_id_c564eba6_fk_auth_user_id` ON `kitty_glow_db`.`django_admin_log` (`user_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `kitty_glow_db`.`django_migrations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kitty_glow_db`.`django_migrations` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `kitty_glow_db`.`django_migrations` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `app` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `applied` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `kitty_glow_db`.`django_session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kitty_glow_db`.`django_session` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `kitty_glow_db`.`django_session` (
  `session_key` VARCHAR(40) NOT NULL,
  `session_data` LONGTEXT NOT NULL,
  `expire_date` DATETIME(6) NOT NULL,
  PRIMARY KEY (`session_key`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;

SHOW WARNINGS;
CREATE INDEX `django_session_expire_date_a5c62663` ON `kitty_glow_db`.`django_session` (`expire_date` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `kitty_glow_db`.`productos_categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kitty_glow_db`.`productos_categoria` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `kitty_glow_db`.`productos_categoria` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `kitty_glow_db`.`productos_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kitty_glow_db`.`productos_usuario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `kitty_glow_db`.`productos_usuario` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `email` VARCHAR(254) NOT NULL,
  `fecha_registro` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;

SHOW WARNINGS;
CREATE UNIQUE INDEX `email` ON `kitty_glow_db`.`productos_usuario` (`email` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `kitty_glow_db`.`productos_pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kitty_glow_db`.`productos_pedido` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `kitty_glow_db`.`productos_pedido` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `fecha_pedido` DATETIME(6) NOT NULL,
  `total` DECIMAL(10,2) NOT NULL,
  `usuario_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `productos_pedido_usuario_id_332f1ab3_fk_productos_usuario_id`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `kitty_glow_db`.`productos_usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;

SHOW WARNINGS;
CREATE INDEX `productos_pedido_usuario_id_332f1ab3_fk_productos_usuario_id` ON `kitty_glow_db`.`productos_pedido` (`usuario_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `kitty_glow_db`.`productos_producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kitty_glow_db`.`productos_producto` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `kitty_glow_db`.`productos_producto` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` LONGTEXT NOT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  `stock` INT NOT NULL,
  `fecha_creacion` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `kitty_glow_db`.`productos_detallepedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kitty_glow_db`.`productos_detallepedido` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `kitty_glow_db`.`productos_detallepedido` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NOT NULL,
  `precio_unitario` DECIMAL(10,2) NOT NULL,
  `pedido_id` BIGINT NOT NULL,
  `producto_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `productos_detalleped_pedido_id_a5db4f9a_fk_productos`
    FOREIGN KEY (`pedido_id`)
    REFERENCES `kitty_glow_db`.`productos_pedido` (`id`),
  CONSTRAINT `productos_detalleped_producto_id_01818576_fk_productos`
    FOREIGN KEY (`producto_id`)
    REFERENCES `kitty_glow_db`.`productos_producto` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;

SHOW WARNINGS;
CREATE INDEX `productos_detalleped_pedido_id_a5db4f9a_fk_productos` ON `kitty_glow_db`.`productos_detallepedido` (`pedido_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `productos_detalleped_producto_id_01818576_fk_productos` ON `kitty_glow_db`.`productos_detallepedido` (`producto_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `kitty_glow_db`.`productos_productocategoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kitty_glow_db`.`productos_productocategoria` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `kitty_glow_db`.`productos_productocategoria` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `categoria_id` BIGINT NOT NULL,
  `producto_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `productos_productoca_categoria_id_e36ad52e_fk_productos`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `kitty_glow_db`.`productos_categoria` (`id`),
  CONSTRAINT `productos_productoca_producto_id_2b62dd1f_fk_productos`
    FOREIGN KEY (`producto_id`)
    REFERENCES `kitty_glow_db`.`productos_producto` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;

SHOW WARNINGS;
CREATE INDEX `productos_productoca_categoria_id_e36ad52e_fk_productos` ON `kitty_glow_db`.`productos_productocategoria` (`categoria_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `productos_productoca_producto_id_2b62dd1f_fk_productos` ON `kitty_glow_db`.`productos_productocategoria` (`producto_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `kitty_glow_db`.`productos_reseña`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kitty_glow_db`.`productos_reseña` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `kitty_glow_db`.`productos_reseña` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `calificacion` INT NOT NULL,
  `comentario` LONGTEXT NOT NULL,
  `fecha_reseña` DATETIME(6) NOT NULL,
  `producto_id` BIGINT NOT NULL,
  `usuario_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `productos_reseña_producto_id_e805d434_fk_productos_producto_id`
    FOREIGN KEY (`producto_id`)
    REFERENCES `kitty_glow_db`.`productos_producto` (`id`),
  CONSTRAINT `productos_reseña_usuario_id_99166403_fk_productos_usuario_id`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `kitty_glow_db`.`productos_usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_spanish_ci;

SHOW WARNINGS;
CREATE INDEX `productos_reseña_producto_id_e805d434_fk_productos_producto_id` ON `kitty_glow_db`.`productos_reseña` (`producto_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `productos_reseña_usuario_id_99166403_fk_productos_usuario_id` ON `kitty_glow_db`.`productos_reseña` (`usuario_id` ASC) VISIBLE;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
