"""
Django settings for kitty_glow project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
# Importar os para manejar las variables de entorno
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
from dotenv import load_dotenv
from kitty_glow.local_settings import IS_DEPLOYED, DATABASE_DICT
from kitty_glow.logging_settings import *
from kitty_glow.cloud_settings import *

# Carga las variables de entorno del archivo .env
load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
# Construir rutas dentro del proyecto de esta manera: BASE_DIR / 'subdir'.
# from pathlib import Path
# BASE_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "")

# SECURITY WARNING: don't run with debug turned on in production!
# Seguridad: no ejecute con depuración activada en producción!
# Se recomienda que DEBUG sea False en producción
# Se recomienda que DEBUG sea True en desarrollo
DEBUG = not IS_DEPLOYED

# Configuración de la dirección IP y el puerto donde se alojará la aplicación
HOSTING_IP_PORT = os.getenv("HOSTING_IP_PORT", '0.0.0.0:8080')

# Configuración del dominio donde se alojará la aplicación
HOSTING_DOMAIN = os.getenv("HOSTING_DOMAIN", "")

# Configuración de la URL de alojamiento de la aplicación
HOSTING_URL= os.getenv("HOSTING_URL", "")

# Configuración de los hosts permitidos
ALLOWED_HOSTS = ['127.0.0.1', 'localhost', HOSTING_IP_PORT, HOSTING_DOMAIN]

# Configuración de los hosts de confianza para la protección contra falsificación de solicitudes entre sitios (CSRF)
CSRF_TRUSTED_ORIGINS = ['http://*', HOSTING_URL]  

# Application definition
# Definición de aplicaciones

INSTALLED_APPS = [
    'django.contrib.admin', # Administrador de Django
    'django.contrib.auth', # Autenticación
    'django.contrib.contenttypes', # Tipos de contenido
    'django.contrib.sessions', # Sesiones
    'django.contrib.messages', # Mensajes
    'django.contrib.staticfiles', # Archivos estáticos
    'django.contrib.humanize', # Humanizar números
    'whitenoise.runserver_nostatic', # Whitenoise para archivos estáticos
    'accounts.apps.AccountsConfig',  # Sistema de autenticación y usuarios
    'storages', # Almacenamiento en la nube
    'productos',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # Whitenoise para archivos estáticos
    'accounts.middleware.ActiveSessionMiddleware',  # Rastreo de sesiones activas
]

# Session Configuration
# Configuración de sesiones
# https://docs.djangoproject.com/en/5.2/topics/http/sessions/

# Tiempo de inactividad antes de expirar la sesión (30 minutos = 1800 segundos)
SESSION_COOKIE_AGE = 1800  # 30 minutos en segundos

# La sesión expira cuando el usuario cierra el navegador (si no marca "Recordarme")
# Esta configuración se sobrescribe en las vistas de login cuando el usuario marca "Recordarme"
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Actualizar el tiempo de expiración de la sesión en cada request
# Esto significa que si el usuario está activo, la sesión se renueva automáticamente
SESSION_SAVE_EVERY_REQUEST = True

# Nombre de la cookie de sesión
SESSION_COOKIE_NAME = 'sessionid'

# Solo enviar cookie por HTTPS en producción
SESSION_COOKIE_SECURE = IS_DEPLOYED

# Protección contra acceso JavaScript a la cookie de sesión
SESSION_COOKIE_HTTPONLY = True

# Restricción de cookie a same-site
SESSION_COOKIE_SAMESITE = 'Lax'


# URL Configuration
# Configuración de URL
# https://docs.djangoproject.com/en/5.2/topics/http/urls/
ROOT_URLCONF = 'kitty_glow.urls'

# Template Configuration
# Configuración de plantillas
# https://docs.djangoproject.com/en/5.2/topics/templates/
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'kitty_glow', 'templates'),  # Templates globales
            os.path.join(BASE_DIR, 'productos', 'templates'),   # Templates de productos
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'productos.context_processors.cart_and_notifications',  # Custom context processor
            ],
        },
    },
]

# WSGI Configuration
# Configuración de WSGI
WSGI_APPLICATION = 'kitty_glow.wsgi.application'


# Database
# Configuración de la base de datos
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

'''
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
'''

# MySQL Database Configuration for MySQL 8.0+
DATABASES = {
    'default': DATABASE_DICT # Base de datos por defecto
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'accounts.validators.CustomPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-co' # Código de idioma

TIME_ZONE = 'America/Bogota' # Zona horaria
# TIME_ZONE = 'UTC'

USE_I18N = True # Usar internacionalización

USE_L10N = True # Usar localización

USE_TZ = True # Usar zona horaria


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Static files (CSS, JavaScript, Images)
# Archivos estáticos (CSS, JavaScript, imágenes)
# Configura la ruta de los archivos estáticos
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Directorio donde se recolectan todos los archivos estáticos para producción
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Almacenamiento de archivos estáticos para producción (Whitenoise)
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# URL de los archivos estáticos
# Para producción, se usa el URL de los archivos estáticos de Whitenoise
# En desarrollo, se usa el URL local
# NOTA: Asegúrate de que el servidor de desarrollo esté configurado para servir archivos estáticos
# https://docs.djangoproject.com/en/5.2/howto/static-files/#serving-static-files-during-development
STATIC_URL = '/staticfiles/' if IS_DEPLOYED else '/static/'

# Directorios adicionales donde buscar archivos estáticos
# NOTA: No incluir <app>/static/ aquí, Django las encuentra automáticamente
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'kitty_glow', 'static'),
    # Los static de las aplicaciones se descubren automáticamente
]

"""
# Configuración para almacenar archivos estáticos en S3
STATICFILES_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/static/'
"""

# Configuración para almacenar archivos multimedia en el sistema de archivos (S3)
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

if not IS_DEPLOYED:
    MEDIA_URL = '/media/'
else:
    DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/'
    
# Se define el nombre de la carpeta de archivos públicos
PUBLIC_MEDIA = 'publico'

# Custom User Model
# Modelo de usuario personalizado
# https://docs.djangoproject.com/en/5.2/topics/auth/customizing/#substituting
AUTH_USER_MODEL = 'accounts.CustomUser'

# Login/Logout URLs
# URLs de inicio/cierre de sesión
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/accounts/dashboard/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# Configuración de Email
# https://docs.djangoproject.com/en/5.2/topics/email/

# Configuración de Email para Gmail
# Para Gmail, genera una "Contraseña de aplicación" en https://myaccount.google.com/apppasswords
# NO uses tu contraseña normal de Gmail
# Activa la verificación en dos pasos primero

# Backend de email (desarrollo vs producción)
# Desarrollo (emails en consola):
# EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend
# Producción (emails reales vía SMTP):
# EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend

# EMAIL_HOST = smtp.gmail.com # Host de Gmail
# EMAIL_PORT = 587 # Puerto de Gmail
# EMAIL_USE_TLS = True # Usar TLS
# EMAIL_HOST_USER = tu-email@gmail.com # Tu email de Gmail
# EMAIL_HOST_PASSWORD = tu-contraseña-de-aplicación-de-google # Contraseña de aplicación de Gmail
# DEFAULT_FROM_EMAIL = tu-email@gmail.com # Email de remitente

# Si IS_DEPLOYED es True, se usa el backend de SMTP - Gmail (emails reales con HTML)
# Si IS_DEPLOYED es False, se usa el backend de Consola (emails en texto plano en terminal)

if IS_DEPLOYED:
    # Producción: Enviar emails reales por SMTP
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
    EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
    EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
    EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
    DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)
else:
    # Desarrollo: Mostrar emails en la consola/terminal
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    # En desarrollo no se necesitan credenciales SMTP
    EMAIL_HOST = 'localhost'
    EMAIL_PORT = 25
    EMAIL_USE_TLS = False
    EMAIL_HOST_USER = ''
    EMAIL_HOST_PASSWORD = ''
    DEFAULT_FROM_EMAIL = 'noreply@kitty-glow-dev.local'

